### ISSUE TITLE
圖片說明文字調整，縮小文字

### ISSUE THREAD

**Issue by purple1007** [purple1007/new-tailwind-theme#45]
圖片說明文字需調整樣式：
1. 文字縮小、顏色淡一點
2. 距離圖片近一點
3. `.wp-caption` 須限制寬度：

```css
.wp-caption {
  width: 100% !important;
}
```
4. 使用的 `class` : `.wp-caption .wp-caption-text` (父層 class : `.wp-caption`)

![截圖 2021-12-05 下午1 47 31](https://user-images.githubusercontent.com/40792376/144735315-ad4f5ec5-3fe5-4da1-bef5-d1f30b429fc2.png)
